version: "3.9"

services:
  neo4j:
    build: 
      dockerfile: neo4j-dockerfile  
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/logs:/logs"
    
  php:
    build: 
      dockerfile: php-dockerfile
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"   
    depends_on:
      - "neo4j"

  python:
    build:
      dockerfile: python-dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "neo4j"

networks:
  default:
    driver: bridge
    