version: "3.9"

services:
  neo4j:
    build: 
      dockerfile: neo4j-dockerfile  
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/logs:/logs"
    depends_on:
      - "php"

  php:
    build: 
      dockerfile: php-dockerfile
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"   

networks:
  default:
    driver: bridge
    